wip: SEO and markup edits
jamstack/jamstack.org pull request #361
Opened 2020-10-01 16:07 UTC by scottmathson

work-in-progress pr/branch for Scott to add metadata and optimize markup throughout, prior to launch

2020-10-01 16:55 UTC, scottmathson commented
fyi @philhawksworth this series of commits here adds trailing slashes so as to resolve to a `200` right away versus `301` happening due to missing `/` - this helps when bots crawl to pass page equity across directly and avoid redirect chains.

![trailing slash commits](https://user-images.githubusercontent.com/25587929/94839710-9a344900-03d4-11eb-836f-d845e7a6f300.png)
ex: https://github.com/jamstack/jamstack.org/pull/361/commits/14980a4bc93ac68823ec34888311cdb620b6eb7f

2020-10-01 17:13 UTC, zachleat requested changes
Just a few minor suggestions

2020-10-01 17:13 UTC, zachleat commented on src/site/_includes/components/generator-card.njk
> +    <a href="{{ item.data.title | slug}}/" >{{ item.data.title }}</a>
```
<a href="{{ item.url }}">{{ item.data.title }}</a>
```

would be better here (and will have the trailing slash)

2020-10-01 17:13 UTC, zachleat commented on src/site/_includes/components/cms-card.njk
> +    <a href="{{ item.data.title | slug}}/" >{{ item.data.title }}</a>
```html
<a href="{{ item.url }}">{{ item.data.title }}</a>
```

same as the other, would be better here (and will have the trailing slash)

2020-10-01 17:13 UTC, zachleat commented on .eleventy.js
> +  eleventyConfig.addLayoutAlias('site', 'layouts/base.njk');
I don’t know if we need this? Doesn’t seem to be used anywhere

2020-10-01 17:14 UTC, scottmathson commented on src/site/_includes/components/generator-card.njk
> +    <a href="{{ item.data.title | slug}}/" >{{ item.data.title }}</a>
ohhh very nice, thanks!

2020-10-01 17:15 UTC, scottmathson commented on .eleventy.js
> +  eleventyConfig.addLayoutAlias('site', 'layouts/base.njk');
using in base.njk - not familiar with config setup here, but used so as to reference `site.title` in `base.njk`

2020-10-01 17:23 UTC, scottmathson commented on .eleventy.js
> +  eleventyConfig.addLayoutAlias('site', 'layouts/base.njk');
https://github.com/jamstack/jamstack.org/pull/361/commits/d6034ebfc68023855d73902101207dd9e5a166a1
https://github.com/jamstack/jamstack.org/pull/361/commits/0f1b3d31236b75edb3dd5c05ad32a26ae030d917
https://github.com/jamstack/jamstack.org/pull/361/commits/eb4ffe6113b69fc8ed2e36d31c5e3911c9ae124c

2020-10-02 16:08 UTC, philhawksworth approved these changes

2020-10-02 16:14 UTC, merged