Add BagelDB to Jamstack
jamstack/jamstack.org pull request #457
Opened 2020-11-19 18:15 UTC by bchalk101

Adding BagelDB - bageldb.com with description and image to Jamstack

2021-01-19 14:57 UTC, huguestennier requested changes
Looking good! Can you fix the Signup link? and we'll be able to add it in.

2021-01-19 14:57 UTC, huguestennier commented on src/site/headless-cms/bageldb.md
> +Signup to BagelDB [here](app.bageldb.com/signup)
This needs to be an absolute link

2021-01-19 16:39 UTC, bchalk101 commented on src/site/headless-cms/bageldb.md
> +Signup to BagelDB [here](app.bageldb.com/signup)
Update to an absolute link

2021-03-18 10:05 UTC, bchalk101 commented
Hi peeps, wondering if I've missed anything that still requires changes?

2021-07-21 15:32 UTC, zachleat approved these changes

2021-07-21 15:33 UTC, merged

2021-07-21 15:33 UTC, zachleat commented
Merged, Thank you!