Added goonlinetools.com
jamstack/jamstack.org pull request #489
Opened 2020-12-25 16:13 UTC by rahulkumarsingh73690

2021-01-19 15:11 UTC, huguestennier commented
Can you resize the thumbnail to the right 596x396 size please? https://github.com/jamstack/jamstack.org#contribute-a-site-example

2021-01-19 16:38 UTC, rahulkumarsingh73690 commented
> Can you resize the thumbnail to the right 596x396 size please? https://github.com/jamstack/jamstack.org#contribute-a-site-example

Image resized as per your request

2021-06-03 06:21 UTC, rahulkumarsingh73690 commented
Please review this PR  @tabar @huguestennier

2021-07-21 15:56 UTC, zachleat requested changes
I think the extension on the yaml file needs to be `.yaml` too.

2021-07-21 15:56 UTC, zachleat commented on src/site/_data/examples/goonlinetools.yml
> +thumbnailurl: /img/examples/t2-media.png
I think this is wrong, right? Needs to match the other file’s filename

2021-07-22 07:52 UTC, rahulkumarsingh73690 commented on src/site/_data/examples/goonlinetools.yml
> +thumbnailurl: /img/examples/t2-media.png
Fixed

2021-08-05 18:16 UTC, huguestennier commented
Unless i'm mistaken, the website doesn’t look like the screen shot. Can you update it?

2021-08-08 15:13 UTC, rahulkumarsingh73690 commented
@huguestennier Added latest image

2021-08-23 13:54 UTC, merged

2021-08-23 13:54 UTC, huguestennier commented
🎉