Streamlining
jamstack/jamstack.org pull request #756
Opened 2022-05-17 21:45 UTC by domitriusclark

2022-06-07 15:45 UTC, philhawksworth commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMGNiNWEyZmYtOWM4ZS00ZDRkLWFiYzAtYWYyZDRiY2QwZTdhIiwiZGVwbG95X2lkIjoiNjI4NDFhZjI1YTdjNTUwMDA4MDAzZTRmIiwiaWQiOiJlNzczMzllNy1hYzcxLTRhNTYtOTk1OC03NDAzMjBhYjIzOGQifQ==)

These two sections are the main call out on this page. If people only read a little, it should be these. So I think they should get a bit of a call out / special visual treatment. Especially the first one. We're suggesting this is THE definition.

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Edge 102.0.1245.30 on Mac OS 10.15.7
Viewport:  1497 x 1146 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-756--jamstack-site.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Edge&browser_version=102.0&resolution=1497x1146&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-756--jamstack-site.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62841af25a7c550008003e4f&commentID=629f729e23399224130e6abc&resolution=resolved)

2022-06-07 15:48 UTC, philhawksworth commented
I'd make these bullet points to make them even easy to digest

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMGNiNWEyZmYtOWM4ZS00ZDRkLWFiYzAtYWYyZDRiY2QwZTdhIiwiZGVwbG95X2lkIjoiNjI4NDFhZjI1YTdjNTUwMDA4MDAzZTRmIiwiaWQiOiIzOTBiMzE2ZC01MDFiLTRkZjgtYmU4YS0wNGU1OGU0YzA0ZDgifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Edge 102.0.1245.30 on Mac OS 10.15.7
Viewport:  1497 x 1146 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-756--jamstack-site.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Edge&browser_version=102.0&resolution=1497x1146&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-756--jamstack-site.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62841af25a7c550008003e4f&commentID=629f7334fcb0b524afceea01&resolution=resolved)

2022-06-07 15:50 UTC, philhawksworth commented
While this is true... I think we can remove it. It is covered in the opening definition and the benefit of explaining further doesn't feel like it outweighs the extra noise/info.

 ![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMGNiNWEyZmYtOWM4ZS00ZDRkLWFiYzAtYWYyZDRiY2QwZTdhIiwiZGVwbG95X2lkIjoiNjI4NDFhZjI1YTdjNTUwMDA4MDAzZTRmIiwiaWQiOiIwN2Q4MWVjNy0yM2YwLTRhM2MtODAxMy1iM2ZhN2JjNTAzMzMifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Edge 102.0.1245.30 on Mac OS 10.15.7
Viewport:  1497 x 1146 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-756--jamstack-site.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Edge&browser_version=102.0&resolution=1497x1146&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-756--jamstack-site.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62841af25a7c550008003e4f&commentID=629f73ce524b22233fed7b5d&resolution=resolved)

2022-06-07 15:54 UTC, philhawksworth commented
I think we can make this page feel more digestible by creating more whitespace between these sections, and also by ensuring generous space between the "Why Jamstack" section and the definitions above.

It might also be worth attempting to make each of these Why Jamstack sections a little more concise. But we can wordsmith that later.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMGNiNWEyZmYtOWM4ZS00ZDRkLWFiYzAtYWYyZDRiY2QwZTdhIiwiZGVwbG95X2lkIjoiNjI4NDFhZjI1YTdjNTUwMDA4MDAzZTRmIiwiaWQiOiI0ZjM5M2EwNS1jOGI0LTQ2ZDUtYjExNC1jNTVhZDc3YjcwYzUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Edge 102.0.1245.30 on Mac OS 10.15.7
Viewport:  1497 x 1146 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-756--jamstack-site.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Edge&browser_version=102.0&resolution=1497x1146&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-756--jamstack-site.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62841af25a7c550008003e4f&commentID=629f74d356a6fa213eecb55e&resolution=resolved)

2022-07-08 10:47 UTC, philhawksworth commented on src/css/tailwind.css
> +    @apply text-white text-3xl font-bold leading-none mb-2 underline;
Adding the underline makes these headings look like links. I'd avoid that

2022-07-08 10:48 UTC, philhawksworth requested changes
I'd like to contribute more to this PR on its way to main... but it's in your own repo rather than in a branch on the jamstack.org repo, which makes it a little tricky.

2022-07-09 15:15 UTC, jlengstorf approved these changes
Minor edit for clarity.

2022-07-09 15:15 UTC, jlengstorf commented on src/site/index.njk
> +      <p>Jamstack is an architectural approach that decouples the web experience layer from data and business logic, improving flexibility, scalability, performance, and maintainability. Jamstack rem
```suggestion
      <p>Jamstack is an architectural approach that decouples the web experience layer from data and business logic, improving flexibility, scalability, performance, and maintainability. Jamstack removes the need for business logic to dictate the web experience. It enables a composable architecture for the web where custom logic and 3rd party services are consumed through APIs.</p>
```

2022-07-09 18:56 UTC, jlengstorf approved these changes
Ship it! Thank you!

2022-07-09 19:03 UTC, merged